version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    labels:
      - "type: dependencies"
      - "javascript"
    open-pull-requests-limit: 10
    groups:
      vitest:
        patterns:
          - "*vitest*"
      rollup:
        patterns:
          - "@rollup/*"
          - "rollup"
          - "rollup-*"
      eslint:
        patterns:
          - "eslint"
          - "eslint-*"
          - "@eslint/*"
      typescript-eslint:
        patterns:
          - "typescript-eslint*"
          - "@typescript-eslint/*"
      postcss:
        patterns:
          - "postcss"
          - "postcss-*"
      svelte:
        patterns:
          - "svelte"
          - "svelte-*"
      prettier:
        patterns:
          - "prettier"
          - "prettier-*"
      tailwindcss:
        patterns:
          - "tailwindcss"
          - "@tailwindcss/*"

  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "type: dependencies"
      - "java"
    groups:
      shedlock:
        patterns:
          - "net.javacrumbs.shedlock:*"
      jollyday:
        patterns:
          - "de.focus-shift:jollyday-*"

  - package-ecosystem: "github-actions"
    directory: "/.github/workflows"
    schedule:
      interval: "weekly"
    labels:
      - "type: dependencies"
      - "github_actions"

  - package-ecosystem: "docker-compose"
    directories:
      - "/.examples/docker-compose"
    schedule:
      interval: "weekly"
