zeiterfassung:
  mail:
    from: zeiterfassung@localhost
    fromDisplayName: zeiterfassung
    replyTo: replyto@localhost
    replyToDisplayName: replyto
  security:
    oidc:
      login-form-url: ''

server:
  compression:
    enabled: true

spring:
  datasource:
    password: zeiterfassung_app_password
    url: jdbc:postgresql://localhost:5432/zeiterfassung
    username: zeiterfassung_app_user
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    properties:
      hibernate:
        envers:
          modified_column_naming_strategy: improved
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-main.xml
    analytics-enabled: false
  mail:
    host: localhost
    password:
    port:
    username:
  messages:
    basename: messages,launchpad-core
    fallback-to-system-locale: false
  web:
    resources:
      cache:
        cachecontrol:
          no-cache: false
          no-store: false
        period: 365
      chain:
        strategy:
          content:
            enabled: true
            paths: /**
  threads:
    virtual:
      enabled: true
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.amqp.RabbitAutoConfiguration

info:
  app:
    name: "@project.name@"
    version: "@project.version@"

management:
  health:
    rabbit:
      enabled: false
    mail:
      enabled: false
  endpoint:
    prometheus:
      access: none
  endpoints:
    web:
      exposure:
        include: health, info
