version: '2.2'
services:
  rabbitmq:
    image: rabbitmq:3.10-management
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - '5672:5672'
      - '15672:15672' # rabbit mq admin ui
  keycloak:
    image: registry.bitbordell.de/focus-shift/containers/keycloak:19.0.2-development-1
    environment:
      KC_HTTP_PORT: 8090
      KC_HTTP_RELATIVE_PATH: /auth
      KC_METRICS_ENABLED: 'true'
      KC_HEALTH_ENABLED: 'true'
      KC_HOSTNAME_STRICT: 'false'
      KC_HOSTNAME_STRICT_HTTPS: 'false'
    ports:
      - '8090:8090'
