name: Build

on:
  push:
    paths-ignore:
      - ".examples/**"
      - ".githooks/**"
      - "docker/**"
    branches:
      - main
  pull_request:
    paths-ignore:
      - ".examples/**"
      - ".githooks/**"
      - "docker/**"
  workflow_dispatch:

env:
  MAVEN_ARGS: "--no-transfer-progress --errors --fail-at-end --show-version"
  PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1

jobs:
  build:
    name: Build
    runs-on: ubuntu-24.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v6

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          distribution: 'liberica'
          java-version-file: ".tool-versions"
          cache: 'maven'

      - name: Build
        run: ./mvnw --no-transfer-progress -DskipTests clean package
