name: Mark issue as deplanned

on:
  issues:
    types: [ demilestoned ]

jobs:
  apply-label:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/github-script@v7
        name: Add label 'status new' to issue when demilestoned
        with:
          github-token: ${{github.token}}
          script: |
            github.rest.issues.addLabels({
              ...context.repo,
              issue_number: context.issue.number,
              labels: ['status: new']
            })
            .catch(e => { console.log(e.message) })
      - uses: actions/github-script@v7
        name: Remove label 'status planned' to issue when demilestoned
        with:
          github-token: ${{github.token}}
          script: |
            github.rest.issues.removeLabel({
              ...context.repo,
              issue_number: context.issue.number,
              name: 'status: planned'
            })
            .catch(e => { console.log(e.message) })
