name: Release Trigger

on:
  workflow_dispatch:
    inputs:
      milestoneName:
        description: 'Milestone Name'
        required: true
        default: 'Name of the Milestone'
      releaseVersion:
        description: 'Release version'
        required: true
        default: 'x.xx.x'
      nextVersion:
        description: 'Next version'
        required: true
        default: 'x.xx.x-SNAPSHOT'

env:
  MAVEN_ARGS: "--no-transfer-progress --errors --fail-at-end --show-version"
  PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1  # required browsers are installed below

jobs:
  run-unit-and-integration-tests:
    name: "Run unit and integration tests"
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - uses: actions/setup-java@v4
        with:
          distribution: 'liberica'
          java-version: 21
          cache: 'maven'

      - name: Build
        run: ./mvnw verify -Dgroups="!ui"

  run-ui-test:
    name: "Run UI tests"
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        browser: ["chromium", "firefox", "webkit"]
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-ui-test-${{ matrix.browser }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'liberica'
          java-version: 21
          cache: 'maven'

      - name: Install Playwright Browsers (UI tests)
        run: ./mvnw exec:java -e -D exec.mainClass=com.microsoft.playwright.CLI -D exec.classpathScope="test" -D exec.args="install --with-deps ${{matrix.browser}}"

      - name: Test
        run: ./mvnw dependency:go-offline verify -Pui-test -Dbrowser=${{matrix.browser}}

      - name: Upload artifacts of failed tests
        uses: actions/upload-artifact@v4
        if: ${{ always() && hashFiles('target/ui-test/**/FAILED-*') != '' }}
        with:
          name: failed-ui-tests
          path: target/ui-test/**/FAILED-*

  create-tag-and-release-notes:
    name: "Create tag and release notes"
    needs:
      - run-unit-and-integration-tests
      - run-ui-test
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Setup git user
        uses: fregante/setup-git-user@v2

      - name: Create Release Notes
        uses: spring-io/github-changelog-generator@v0.0.12
        with:
          milestone: ${{ github.event.inputs.milestoneName }}
          changelog-file: ${{format('{0}{1}{2}', '.chglog/', github.event.inputs.releaseVersion, '.md')}}
          config-file: '.github/release-notes.yml'
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit Release Notes
        run: |
          git add .chglog/*.md
          git commit -m "[skip ci] Add release notes for version ${{ github.event.inputs.releaseVersion }}"
      - name: Push Release Notes
        uses: ad-m/github-push-action@v0.8.0
        with:
          github_token: ${{ secrets.AM_PAT }}
          branch: ${{ github.ref }}

      - name: Set release version
        run: ./mvnw versions:set -DnewVersion=${{ github.event.inputs.releaseVersion }}
      - name: Commit release version
        run: git add pom.xml && git commit -m "New Release Version zeiterfassung-${{ github.event.inputs.releaseVersion }}"
      - name: Add release tag
        run: git tag -a -m "zeiterfassung-${{ github.event.inputs.releaseVersion }}" zeiterfassung-${{ github.event.inputs.releaseVersion }}
      - name: Push release version
        uses: ad-m/github-push-action@v0.8.0
        with:
          github_token: ${{ secrets.AM_PAT }}
          branch: ${{ github.ref }}

      - name: Set new snapshot version
        run: ./mvnw versions:set -DnewVersion=${{ github.event.inputs.nextVersion }}
      - name: Commit new snapshot version
        run: git add pom.xml && git commit -m "Prepare Next Snapshot Version zeiterfassung-${{ github.event.inputs.nextVersion }}"
      - name: Push snapshot commit
        uses: ad-m/github-push-action@v0.8.0
        with:
          github_token: ${{ secrets.AM_PAT }}
          branch: ${{ github.ref }}
